kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsan-default-storage-policy
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagePolicyName: "vSAN Default Storage Policy"
